from utils.loghandler import catch_exception
import sys
sys.excepthook = catch_exception